#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ezmorph
Version  : 1
Release  : 2
URL      : https://downloads.sourceforge.net/project/ezmorph/ezmorph/ezmorph-1.0.6/ezmorph-1.0.6-sources.jar
Source0  : https://downloads.sourceforge.net/project/ezmorph/ezmorph/ezmorph-1.0.6/ezmorph-1.0.6-sources.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-ezmorph-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-ezmorph package.
Group: Data

%description data
data components for the mvn-ezmorph package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ezmorph/ezmorph/1.0.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ezmorph/ezmorph/1.0.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.jar
/usr/share/java/.m2/repository/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.pom
